// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCURuQsarcXHwWfDk6ZBWlTWvFpM6NjhWM',
    appId: '1:539417967732:web:8c90881fc5b97cc58da521',
    messagingSenderId: '539417967732',
    projectId: 'login-by-firebase-5c61c',
    authDomain: 'login-by-firebase-5c61c.firebaseapp.com',
    storageBucket: 'login-by-firebase-5c61c.appspot.com',
    measurementId: 'G-KP66G4V0PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkAPx-LpzDoZz2XSht5sUFS4ecqI2pZS8',
    appId: '1:539417967732:android:a97f7d4ca9894d058da521',
    messagingSenderId: '539417967732',
    projectId: 'login-by-firebase-5c61c',
    storageBucket: 'login-by-firebase-5c61c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd8RPNjk-kAxEyjzMM_HK4TmMayl9nuj0',
    appId: '1:539417967732:ios:40597fbce9b80a718da521',
    messagingSenderId: '539417967732',
    projectId: 'login-by-firebase-5c61c',
    storageBucket: 'login-by-firebase-5c61c.appspot.com',
    iosBundleId: 'com.example.loginByFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd8RPNjk-kAxEyjzMM_HK4TmMayl9nuj0',
    appId: '1:539417967732:ios:40597fbce9b80a718da521',
    messagingSenderId: '539417967732',
    projectId: 'login-by-firebase-5c61c',
    storageBucket: 'login-by-firebase-5c61c.appspot.com',
    iosBundleId: 'com.example.loginByFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCURuQsarcXHwWfDk6ZBWlTWvFpM6NjhWM',
    appId: '1:539417967732:web:8275899542404a798da521',
    messagingSenderId: '539417967732',
    projectId: 'login-by-firebase-5c61c',
    authDomain: 'login-by-firebase-5c61c.firebaseapp.com',
    storageBucket: 'login-by-firebase-5c61c.appspot.com',
    measurementId: 'G-6YRDDBYZZF',
  );
}
